#
# makefile 
#
# input file for 'make' build tool ( /usr/bin/make )
# to build solution for JUnit sample
#
# @author Dr. Fenwick
# @further Edits by Robert Scheffler 09/21/21
# @version Summer 2018
#
HAMCREST_JAR = /usr/share/java/hamcrest/core-1.1.jar
JUNIT5_JAR = junit-platform-console-standalone-1.2.0.jar 
JUNIT5_RUNNER = org.junit.platform.console.ConsoleLauncher
CKSTYLE_COMMAND =  -jar /usr/local/checkstyle-5.5/checkstyle-5.5-all.jar
CKSTYLE_XML = cs_appstate_checks.xml

default:
	@echo "____________________ defchk, customchk - default or custom checkstyle"
	@echo "________ make defchk"

# makefile syntax
#target-name: files dependent on (can use multiple lines by ending
#             lines with \
#<TAB char>Unix command-line command
#<TAB char>Unix command-line command
#etc.
#Essential that command lines start with single TAB character 

defchk: HelloWorld.java $(CKSTYLE_XML)
#	checkstyle HelloWorld.java
	java $(CKSTYLE_COMMAND) -c $(CKSTYLE_XML) HelloWorld.java


